"""add relationship rating to application

Revision ID: 3bafe71d2725
Revises: 111c943514e6
Create Date: 2025-02-01 13:01:24.507521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bafe71d2725'
down_revision = '111c943514e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('application_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ratings', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'application_id')
    # ### end Alembic commands ###
