"""add deleted field to reviews and comments

Revision ID: 93eeb2208296
Revises: 3bafe71d2725
Create Date: 2025-02-03 17:10:12.791369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import false


# revision identifiers, used by Alembic.
revision = '93eeb2208296'
down_revision = '3bafe71d2725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deleted', sa.Boolean(), server_default=false(), nullable=False, default=False))
    op.add_column('reviews', sa.Column('deleted', sa.Boolean(), server_default=false(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'deleted')
    op.drop_column('comments', 'deleted')
    # ### end Alembic commands ###
